
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Customs Cadet Corps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
          <div className="container">
            <Navbar />
            {children}
          </div>
        </body>
        <Footer />
    </html>
  );
}
